MSBUILD=msbuild.exe

ifneq (,$(CHUCK_DEBUG))
CONFIG=Debug
CHUG_BIN=x64/Debug/PluginHost.chug
else
CONFIG=Release
CHUG_BIN=x64/Release/PluginHost.chug
endif

default: build copy

build: 
	$(MSBUILD) /p:Configuration=$(CONFIG) /p:Platform=x64 PluginHost.vcxproj

copy:
	copy /Y $(subst /,\,$(CHUG_BIN)) .

clean:
	$(MSBUILD) /p:Configuration=$(CONFIG) /p:Platform=x64 /t:Clean PluginHost.vcxproj
	-del /Q PluginHost.chug 2>NUL
