MSBUILD=msbuild.exe

ifneq (,$(CHUCK_DEBUG))
CONFIG=Debug
CHUG_BIN=x64/Debug/PluginHost.chug
else
CONFIG=Release
CHUG_BIN=x64/Release/PluginHost.chug
endif

default: $(CHUG_BIN)

$(CHUG_BIN): 
	$(MSBUILD) /p:Configuration=$(CONFIG) /p:Platform=x64 PluginHost.vcxproj

clean:
	$(MSBUILD) /p:Configuration=$(CONFIG) /p:Platform=x64 /t:Clean PluginHost.vcxproj
