CMAKE=cmake

ifneq (,$(CHUCK_DEBUG))
CONFIG=Debug
else
CONFIG=Release
endif

default: build

build:
	$(CMAKE) -B build -G "Visual Studio 17 2022" -A x64
	$(CMAKE) --build build --config $(CONFIG)

clean:
	-rmdir /S /Q build 2>NUL
	-del /Q PluginHost.chug 2>NUL
